app:
  name: "web_app"
  mode: "dev"
  port: 9090

log:
  level: "debug"
  filename: "web_app.log"
  max_size: 200
  max_age: 30
  max_backups: 7

mysql:
  host: "192.168.1.208"
  port: 3306
  user: "root"
  password: "123456"
  dbname: "app_demo"
  SetMaxOpenConns: 20
  SetMaxIdleConns: 10

redis:
  host: "192.168.1.208"
  port: 6379
  db: 0
  password: huanshao
